logging:
  level:
    com.example: DEBUG
    org.hl7.fhir.common.hapi.validation.validator.VersionSpecificWorkerContextWrapper: WARN
#    org.hl7.fhir.common.hapi.validation.support.SnapshotGeneratingValidationSupport: ERROR