spring:
  application:
    name: demo
  profiles:
    active:
    - dev
    - log_default
    
# Virtual Thread                  
  threads:
    virtual:
      enabled: true 
      
# Fhir Configuration(high performance mode)
#fhir:
#  high-performance-mode: true